terraform import module.iam.aws_iam_group.TSI_Base_Group_PowerUser TSI_Base_Group_PowerUser
terraform import module.iam.aws_iam_policy.TSI_Base_VPC_Flowlog arn:aws:iam::${accountId}:policy/TSI_Base_VPC_Flowlog
terraform import module.iam.aws_iam_policy.TSI_Base_EventBus_Policy arn:aws:iam::${accountId}:policy/TSI_Base_EventBus_Policy
terraform import module.iam.aws_iam_policy.TSI_Base_CrossAccountBucketPolicy arn:aws:iam::${accountId}:policy/TSI_Base_CrossAccountBucketPolicy
terraform import module.iam.aws_iam_policy.TSI_Base_Policy_MFA arn:aws:iam::${accountId}:policy/TSI_Base_Policy_MFA
terraform import module.iam.aws_iam_policy.TSI_Base_S3_DPC_SecDevOps_Policy arn:aws:iam::${accountId}:policy/TSI_Base_S3_DPC_SecDevOps_Policy
terraform import module.iam.aws_iam_role.automationrole TSI_Base_Automation
terraform import module.iam.aws_iam_role.cloudwatcheventrole TSI_Base_EventBus_Role
terraform import module.iam.aws_iam_role.ConfigRecorderRole TSI_AWS_configRole
terraform import module.iam.aws_iam_role.TSI_Base_S3_DPC_SecDevOps_Role TSI_Base_S3_DPC_SecDevOps_Role
terraform import module.iam.aws_iam_role.TSI_Base_2ndLevel_Role TSI_Base_2ndLevel_Role
terraform import module.iam.aws_iam_role.TSI_Base_BackOffice_Role TSI_Base_BackOffice_Role
terraform import module.iam.aws_iam_role.TSI_Base_ManagedServices TSI_Base_ManagedServices
terraform import module.iam.aws_iam_role.TSI_Base_ReadOnlySwitchRole TSI_Base_ReadOnlySwitchRole 
terraform import module.iam.aws_iam_role.TSI_Base_pacbot_ro TSI_Base_pacbot_ro
terraform import module.iam.aws_iam_group_policy_attachment.tsibasegrouppoweruser_administratoraccess TSI_Base_Group_PowerUser/arn:aws:iam::aws:policy/AdministratorAccess
terraform import module.iam.aws_iam_role_policy_attachment.automationrole-attach-s3 TSI_Base_Automation/arn:aws:iam::${accountId}:policy/TSI_Base_S3_DPC_SecDevOps_Policy
terraform import module.iam.aws_iam_role_policy_attachment.automationrole-attach-vpc TSI_Base_Automation/arn:aws:iam::${accountId}:policy/TSI_Base_VPC_Flowlog
terraform import module.iam.aws_iam_role_policy_attachment.configrole-attach-policy-awsconfigrole TSI_AWS_configRole/arn:aws:iam::aws:policy/service-role/AWSConfigRole
terraform import module.iam.aws_iam_role_policy_attachment.configrole-attach-policy-custom TSI_AWS_configRole/arn:aws:iam::${accountId}:policy/TSI_Base_CrossAccountBucketPolicy
terraform import module.iam.aws_iam_role_policy_attachment.eventbusrole-attach-policy TSI_Base_EventBus_Role/arn:aws:iam::${accountId}:policy/TSI_Base_EventBus_Policy
terraform import module.iam.aws_iam_role_policy_attachment.pacbotro-attach-policy-awssupport TSI_Base_pacbot_ro/arn:aws:iam::aws:policy/AWSSupportAccess
terraform import module.iam.aws_iam_role_policy_attachment.pacbotro-attach-policy-guarddutyreadonly TSI_Base_pacbot_ro/arn:aws:iam::aws:policy/AmazonGuardDutyReadOnlyAccess
terraform import module.iam.aws_iam_role_policy_attachment.pacbotro-attach-policy-readonly TSI_Base_pacbot_ro/arn:aws:iam::aws:policy/ReadOnlyAccess
terraform import module.iam.aws_iam_role_policy_attachment.readonlyswitchrole-attach-policy-readonly TSI_Base_ReadOnlySwitchRole/arn:aws:iam::aws:policy/ReadOnlyAccess
terraform import module.iam.aws_iam_role_policy_attachment.s3dpcrole-attach-policy TSI_Base_S3_DPC_SecDevOps_Role/arn:aws:iam::${accountId}:policy/TSI_Base_S3_DPC_SecDevOps_Policy
terraform import module.iam.aws_iam_role_policy_attachment.secondlevelrole-attach-policy TSI_Base_2ndLevel_Role/arn:aws:iam::aws:policy/job-function/SupportUser
terraform import module.iam.aws_iam_role_policy_attachment.tsibackoffice-attach-policy TSI_Base_BackOffice_Role/arn:aws:iam::aws:policy/AWSSupportAccess
terraform import module.sns.aws_cloudformation_stack.TSI_SNS_Topic TSI-SNS-Topic
